spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    ddl-auto: none
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
mailgun:
  username: ${MAILGUN_USERNAME}
  password: ${MAILGUN_PASSWORD}
  emailSender: "5marias.sustentaveis@gmail.com"
  emailReceiver: "5marias.orcamento@gmail.com"

login:
  email: "teste@gmail.com"
  password: "123456"
